language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - nightly
notifications:
  email: false

# Allow for failures when it comes to `nightly` builds not to block the patches
# that pass in supported versions.
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
